insert into search_history(keyword, search_hit) values ('피파', 10);
insert into search_history(keyword, search_hit) values ('호날두', 20);
insert into search_history(keyword, search_hit) values ('메시', 30);
insert into search_history(keyword, search_hit) values ('이승기', 40);
insert into search_history(keyword, search_hit) values ('월드컵', 50);
insert into search_history(keyword, search_hit) values ('스프링', 60);
insert into search_history(keyword, search_hit) values ('자바', 70);
insert into search_history(keyword, search_hit) values ('파이썬', 80);
insert into search_history(keyword, search_hit) values ('뉴스', 90);
insert into search_history(keyword, search_hit) values ( '날씨', 100);
insert into search_history(keyword, search_hit) values ( '기상청', 110);
